export interface User {
  UsrId: number;
  UsrCode: string;
  UsrName: string;
  UsrEmail: string;
  UsrMobile: string;
  UsrUrlId: number;
  UsrBrnId: number;
  UsrCtrId: number;
  UsrImageName: string;
  UsrImg: string;
  UsrPwd: string;
  UsrOtpSignIn: boolean;
  UsrPwdChangeFirstLogin: boolean;
  UsrLastPwdChangeDate: string;
  UsrPwdExpirable: boolean;
  UsrLoginTimeFrom: string;
  UsrLoginTimeTo: string;
  UsrDloginOnHolidays: boolean;
  UsrStsCode: number;
  UsrAddUser: string;
  UsrAddDate: string;
  UsrModUser: string;
  UsrModDate: string;
  UsrEmpId: number | null;
  UsrWlevel: string;
  UsrCBrnId: number;
  UsrWBrnId: number;
  UsrCCmpId: number;
  UsrModId: number;
  UsrType: string;
  UsrSign: string;
  UserDays: any[];
  UsrIsLogin: boolean;
  UsrPwdOther: string;
  UsrAuthLevel2: boolean;
  UsrAuthMode: string;
  UsrPwdExpireDays: number | null;
  UsrOtp: string | null;
  UsrOtpDate: string | null;
  UsrIpAddress: string;
  UsrHideCost: boolean;
  UsrLinkAcmId: number;
  UsrCnfPwd: string;
  UsrModName: string | null;
  UsrModImg: string | null;
  UsrEmpName: string | null;
  UsrEmpCode: string | null;
  StsCode: number;
  Token: string | null;
  UsrLghId: number;
  UsrModRights: any | null;
  UsrUrlName: string;
  UsrLinkAcmName: string;
  UsrLinkAcmCode: string | null;
}
