export class PSOMain {
  psomMKey?: string;
  psomCmpId?: number = 0;
  psomBrnId?: number = 0;
  psomAcmId?: number = 0;
  psomVtype?: string = '';
  psomVNoPrefix?: string = '';
  psomVNoSeq?: 0;
  psomVNo?: '';
  psomVdate?: Date = new Date();
  psomItmCount: number = 0;
  psomItmQty: number = 0;
  psomNetAmount: number = 0;
  psomOrderType?: string = '';
  psomStatus?: string = '';
  psomRemarks?: string = '';
  psomStatusCode?: number = 0;
  psomAddUser?: string = '';
  psomAddDate?: Date = new Date();
  psomModUser?: string = '';
  psomModDate?: Date = new Date();
  psomAcmName?: string = '';
  psomBrnname?: string = '';
  psoDetails?: PSODetail[] = [];
}

export class PSODetail {
  psodPsomMkey?: string = '';
  psodRowNo?: number = 0;
  psodItmId: number = 0;
  psodPack: string = '';
  psodMRP: number = 0;
  psodRate: number = 0;
  psodQty: number = 0;
  psodUnitId: number = 0;
  psodUnitFactor: number = 0;
  psodNetAmount: number = 0;
  psodStock: number = 0;
  psodBaseQty: number = 0;
  psodBaseUnitId: number = 0;
  psodRemarks?: string = '';
  psodItmCode?: string = '';
  psodItmName?: string = '';
}

export class SOMain {
    SomMkey?: string = '';
    SomCmpId?: number=0;
    SomBrnId?: number=0;
    SomFyrId?: number=0;
    SomType?: string='Customer Order';
    SomVtype?: string;
    SomVnoPrefix?: string;
    SomVnoSeq?: number=0;
    SomVnoSuffix?: string='';
    SomVno?: string='';
    SomVdate?: Date | null;
    SomRefNo?: string = '';
    SomRefDate?: Date | null | string = '';
    SomDocType?: string='';
    SomDocNo?: string = '';
    SomAcmId?: number=0;
    SomEmpId?: number=0;
    SomShpBrnId?: any=0;
    SomDlvBy?: string='DATE';
    SomDlvDays?: number=0;
    SomDlvDate?: Date | null;
    //SomDlvBrnId: number | null=0;
    SomDlvLocation?: string =''
    SomDlvMobileNo?: string;
    SomDlvKeyPerson?: string;
    SomDlvAddress1?: string = '';
    SomDlvAddress2?: string = '';
    SomDlvPinCode?: string;
    SomDlvCtyId?: any | null=0;
    SomDlvStaId?: any | null=0;
    SomDlvCntId?: any | null=0;
    SomCrmId?: any | null=0;
    SomDlvGstIn?: string = '';
    SomShpMode?: string='ROAD';
    SomShpDlvDate?: Date | null;
    SomShipper?: string;
    SomPayMethod?: string='CREDIT';
    SomPayTerms?: number=0;
    SomAdvAmt?: number=0;
    SomAdvBank?: string='';
    SomAdvDetail?: string='';
    SomLcTerms?: number=0;
    SomLcDate?: Date | null;
    SomLcExpDate?: Date | null;
    SomLcBank?: string;
    SomCurId?: number | null=0;
    SomCurRate?: number=0;
    SomPriceAt?: string;
    SomGstInclusive?: boolean = false;
    SomGstType?: string;
    SomPos?: string='';
    SomInterState?: string='';
    SomTaxableAmt?: number=0;
    SomGstAmt?: number=0;
    SomBillDisType?: string= '%';
    SomBillDisRate?: number=0;
    SomBillDisAmt?: number=0;
    SomOtherAmt?: number=0;
    SomDlvAmt?: number=0;
    SomPackAmt?: number=0;
    SomTotalAmt?: number=0;
    SomRoundOff?: number=0;
    SomNetAmt?: number=0;
    SomTerms?: any='';
    SomRemarks?: string;
    SomStsCode: number=0;
    SomAddUser?: string;
    SomAddDate?:Date | null;
    SomModUser?: string;
    SomModDate?: Date | null | string = '';
    SomTId?: string;
    SoDetails: SODetail[] = [];
    SomDlvAcmId?: number=0;
    SomUnit?: string='';
    SomStatus?: string = '';
    SomNextDocNo?: string = '';
    SomQty ?: number;
    SomBaseQty? : number;
    SomIsJSonBase?: boolean = false;
    SomBtpCode?: string;
}

export class SODetail {
    SodSomMkey?: string|number=0;
    SodId?: number=0;
    SodType?:string='';
    SodRowNo?: number=0;
    SodRowType?: string='';
    SodItmId?: number=0;
    SodSpec?: string='';
    SodPack?: string='';
    SodQty?: number=0;
    SodFocQty?: number=0;
    SodUntId?: number=0;
    SodUnitFactor?: number=0;
    SodBaseQty?: number=0;
    SodBaseUntId?: number=0;
    SodWeight?: number=0;
    SodMrp?: number=0;
    SodRate?: number=0;
    SodRateUntId?: number | null;
    SodPrice?: number=0;
    SodGrossAmt?: number|string=0;
    SodDisAmt?: number=0;
    SodDisCalcOn1?: number|string=0;
    SodDisType1?: string='';
    SodDisRate1?: number=0;
    SodDisAmt1?: number=0;
    SodDisCalcOn2?: number|string=0;
    SodDisType2?: string='';
    SodDisRate2?: number=0;
    SodDisAmt2?: number=0;
    SodDisCalcOn3?: number|string=0;
    SodDisType3?: string='';
    SodDisRate3?: number=0;
    SodDisAmt3?: number=0;
    SodDisCalcOn4?: number|string=0;
    SodDisType4?: string='';
    SodDisRate4?: number=0;
    SodDisAmt4?: number=0;
    SodTaxableAmt?: number=0;
    SodGstId?: number=0;
    SodGstRate?: number=0;
    SodGstAmt?: number=0;
    SodIgstAmt?: number=0;
    SodCgstAmt?: number=0;
    SodSgstAmt?: number=0;
    SodCessAmt?: number=0;
    SodAcessAmt?: number=0;
    SodOtherGstAmt?: number=0;
    SodExpAmt?: number=0;
    SodNetAmt?: number=0;
    SodSchType?: string='';
    SodSchMkey?: string='';
    SodSchDesc?: string='';
    SodRemarks?: string='';
    SodStock?: number=0;
    SodItmCode?: string = '';
    SodItmName?: string = '';
    SodUntCode?: string = '';
    SodGstCode?: string = '';
}