export interface ItemPrice {
  Batch: string | null;
  Vstock: number;
  Astock: number;
  Rstock: number;
  Fstock: number;
  Ocstock: number;
  Expdate: string | null;
  Pack: string | null;
  Saleprice: number;
  Trfprice: number;
  Dlrprice: number;
  Onlprice: number;
  Costprice: number;
  MarginType: string | null;
  GstRate: number;
  PriceCode: string | null;
  MRP: number;
  MarginCode: string | null;
  MarginRate: number;
  AvgCostprice: number;
  WogCost: number;
  Mkey: string | null;
  Rowno: number;
  Subrowno: number;
  Code: string | null;
  Description: string | null;
  Qty: number;
  Unit: string | null;
  ItmPriceMethod: string | null;
  OnlMarkRate: number;
  DlrMarkRate: number;
  TrfMarkRate: number;
  SaleMarkRate: number;
  SaleMarka: string | null;
  TrfMarka: string | null;
  DlrMarka: string | null;
  OnlMarka: string | null;
  ItmExpirable: boolean;
  Stock: number;
  UnitFactorType: string;
  UnitFactor: number;
  ShowPrice: number;
  AddDate: string | null;
  RefDate: string | null;
}

export interface Product {
  ItmId: number;
  ItmCode: string;
  ItmName: string;
  ItmPrintAs: string;
  ItmSpec: string;
  ItmImageFile: string;
  ItmImage: string;
  ItmMrp: number;
  Itemprices: ItemPrice[];
  ItmQty: number;
  ItmPackUntCode: string;
  ItmUntId: number;
  ItmBaseUntId: number;
  ItmBaseUntCode: string;
  ItmDivId: number | null;
  ItmCatId: number | null;
  ItmSubCatId: number | null;
  ItmBrandId: number | null;
  ItmBaseId: number | null;
  ItmVarientId: number | null;
  ItmSeasonId: number | null;
  ItmYearId: number | null;
  ItmOccaId: number | null;
  ItmGenderId: number | null;
  ItmSizeId: number | null;
  ItmColorId: number | null;
  ItmAtt1Id: number | null;
  ItmAtt2Id: number | null;
  ItmAtt3Id: number | null;
  ItmAtt4Id: number | null;
}
